server:
  port: 8002
spring:
  data:
    elasticsearch:
      host: 192.168.130.130
      port: 9200
  elasticsearch:
    rest:
      uris: 192.168.130.130:9200
  redis:
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    host: 192.168.130.130
    database: 0
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 300
        # 连接池中的最小空闲连接
        max-idle: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
        # 连接超时时间（毫秒）
        timeout: 5000
  application:
    name: service-goods
  #数据库连接信息
  datasource:
    name: test
    url: jdbc:mysql:///spring-goods?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT
    username: root
    password: 1111
    # 使⽤druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

# 注册中⼼配置
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka #http://eureka7001.com:7001/eureka
#defaultZone:http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true #访问路径可以显示IP地址
# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'

mybatis:
  type-aliases-package: cn.hrk.spring.goods.domain
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
##开启驼峰
mapper :
  mappers: cn.hrk.common.base.BaseMapper #扫描基类接口
  identity: mysql
logging:
  level :
    cn:
      hrk:
        spring:
          mapper: debug

aliyun:
  file:
    endpoint: http://oss-cn-hangzhou.aliyuncs.com
    accessKeyId: LTAI4Fovzyr2Bqu9MptWJzTK
    accessKeySecret: g5DucWzop3NYzpKJ3XhGlJSpk7h9lD
    bucketName: springshop
    folder: upload
    webUrl: https://springshop.oss-cn-hangzhou.aliyuncs.com
